In [21]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [22]:
df=pd.read_csv('LIquidAirRegu.csv')
df.head(10)

,power,energy,effi,storage,charge,discharge,profit,Revenew
0,0,0,0.00,0,0.000000,0.0,0,0.000000
1,110000,2000,0.35,[342.67859007],52.960349,2.8,[82773.63063946],191575.178649
2,170000,2000,0.35,[236.97750181],29.507464,2.8,[59811.98479975],149619.257448
3,230000,2000,0.35,[197.12483224],20.205461,2.8,[44132.16166133],129001.773497
4,290000,2000,0.35,[161.51122249],15.015794,2.8,[31604.88845522],112817.023811
5,350000,2000,0.35,[130.41039812],11.166197,2.8,[21180.76090242],98260.530733
6,410000,2000,0.35,[107.97599116],8.531048,2.8,[12243.96581892],86869.465043
7,470000,2000,0.35,[94.20927685],6.808857,2.8,[4313.28870578],78764.189135
8,530000,2000,0.35,[0.],0.000000,0.0,[0.],0.000000
9,490000,2000,0.35,[90.5370768],6.367482,2.8,[1829.73415824],76519.485688

In [23]:
a=np.zeros(len(df.storage))
for i in np.arange(len(df.storage)):
    a[i]=float(df.storage[i].strip("[]"))
df.storage=a

In [24]:
a=np.zeros(len(df.profit))
for i in np.arange(len(df.profit)):
    a[i]=float(df.profit[i].strip("[]"))
df.profit=a

In [25]:
A=df.query('profit<100 & profit>0 ').reset_index()
A=A.drop_duplicates(subset=['energy','effi'], keep='last').reset_index()
import openpyxl
from openpyxl import load_workbook

A.to_csv('PTPReg')